; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = ./config

[env]
; 框架
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.34/platform-espressif32.zip
board = board
framework = arduino, espidf
board_build.embed_txtfiles =
  managed_components/espressif__esp_insights/server_certs/https_server.crt
  managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
  managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
  managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt
; TTL速度
upload_speed = 921600
monitor_speed = 115200
; 文件系统配置
board_build.partitions = ./config/partition.csv
board_build.filesystem = spiffs
; 依赖库
lib_deps =
  thijse/ArduinoLog@^1.1.1
  xylopyrographer/LiteLED@^3.0.0
; 编译标志
build_flags = 
  -D CFG_TUSB_MCU=OPT_MCU_ESP32S3
  -D CFG_TUSB_CONFIG_FILE=\"$PROJECT_DIR/include/module/usb/tusb_config.h\"

[env:release]

[env:debug]

; 请手动执行“Upload Filesystem Image”来上传文件，会自动上传“data”目录下的文件