; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = ./config

[env]
; 框架
platform = espressif32
board = board
framework = arduino, espidf
board_build.sdkconfig = config/sdkconfig
; TTL速度
upload_speed = 921600
monitor_speed = 115200
; 文件系统配置
board_build.partitions = ./config/partition.csv
board_build.filesystem = spiffs

[env:release]

[env:debug]

; 请手动执行“Upload Filesystem Image”来上传文件，会自动上传“data”目录下的文件