#pragma once

#define TASK_AUDIO_ENCODER_CORE 0
#define TASK_AUDIO_ENCODER_PERIOD 3 // 这里必须和编码器轮询周期一样！
#define TASK_AUDIO_ENCODER_PRIORITY 2
#define TASK_AUDIO_ENCODER_STACK 4096

#define TASK_TUSB_CORE 1
#define TASK_TUSB_PRIORITY 3
#define TASK_TUSB_STACK 4096

#define TASK_RF_CORE 1
#define TASK_RF_PERIOD 1
#define TASK_RF_PRIORITY 1
#define TASK_RF_STACK 4096

#define TASK_SYSTEM_CORE 1
#define TASK_SYSTEM_PERIOD 1000
#define TASK_SYSTEM_PRIORITY 1
#define TASK_SYSTEM_STACK 3072